//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pizzaria1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Comanda
    {
        public int cod_produs { get; set; }
        public int cod_furnizor { get; set; }
        public System.DateTime data_venire { get; set; }
        public int cantitate { get; set; }
        public int cod_comanda { get; set; }
    
        public virtual Furnizori Furnizori { get; set; }
        public virtual Produse Produse { get; set; }
    }
}
