//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pizzaria1
{
    using System;
    using System.Collections.Generic;
    
    public partial class comanda_view
    {
        public int cod_comanda { get; set; }
        public string nume { get; set; }
        public int cantitate { get; set; }
        public System.DateTime data_venire { get; set; }
        public string nume_furnizor { get; set; }
    }
}
