//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pizzaria1
{
    using System;
    using System.Collections.Generic;
    
    public partial class furnizor_view
    {
        public int Cod_Furnizor { get; set; }
        public string Nume { get; set; }
        public int Cod_Fiscal { get; set; }
        public string Adresa { get; set; }
    }
}
