//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pizzaria1
{
    using System;
    using System.Collections.Generic;
    
    public partial class produse_view
    {
        public int cod_produs { get; set; }
        public string nume { get; set; }
        public float pret { get; set; }
        public string depozit { get; set; }
        public string categorie { get; set; }
    }
}
